- name: configure frontend
  hosts: frontend
  become: yes
  
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent 
  
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: present
  
  - name: download frontend code
    ansible.builtin.get_url:
      url: curl -o /tmp/frontend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: extract code 
    ansible.builtin.unarchive:
      src: unzip /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy backend service 
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart the nginx
    ansible.builtin.service:
      name: nginx
      start: restarted
      



